#!/bin/bash

#SBATCH --job-name="STAGE-POSE"
#SBATCH --partition=g2
#SBATCH --output=job.log
#SBATCH --error=job.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus=1
#SBATCH --requeue
#SBATCH -t 48:00:00


# Main command goes here
conda activate bat
source run-local.bash

exit

